### ISSUE TITLE
combining magical_attributes alters original attributes

### ISSUE THREAD

**Issue by mgamperl** [dschu012/d2s#10]
Hi,

In the progress of using your api for a project of mine I discovered the following behaviour:

During the process of combining magical_attributes the original magical_attributes get altered so when using the resulting object to write the items back to a file the magical_attributes are wrong.

Example: 

Original data:
![image](https://user-images.githubusercontent.com/7489615/116155362-47144180-a6ea-11eb-969b-625c98343664.png)

After writing the item:
![image](https://user-images.githubusercontent.com/7489615/116155657-ac683280-a6ea-11eb-9c19-aef058996a23.png)

As you can see the enhanced damage is incorrectly written with additional 100%.

The problem lies here:
``` typescript
function _allAttributes(
  item: types.IItem,
  constants: types.IConstantData
): types.IMagicProperty[] {
  let socketed_attributes = [] as types.IMagicProperty[];
  if (item.socketed_items) {
    for (const i of item.socketed_items) {
      socketed_attributes = socketed_attributes.concat(
        //TODO: deep copy
        ...i.magic_attributes
      );
    }
  }
  let magic_attributes = item.magic_attributes || [];
  let runeword_attributes = item.runeword_attributes || [];
  return [
    ...[],
    //TODO: deep copy
    ...magic_attributes,
    //TODO: deep copy
    ...runeword_attributes,
    //TODO: deep copy
    ...socketed_attributes,
  ].filter((attribute) => attribute != null);
}
``` 
I can fix this and submit a pull request but I wanted to clarify which solution you prefer:
1) deep copy using i.e lodash
2) deep copy using the hacky way with JSON.parse(JSON.stringify())
3) deep copy using a custom function
4) deep copy using the spread operator for all the nested levels

I would propose to use solution 1 or 2 as the other two seem to be error prone or too much effort to solve such a small problem. 
Maybe you have a better idea then please let me know.

**Comment by mgamperl** [comment]
created pull request #16 fixing it by using solution 2. after discussion I will update accordingly.

**Comment by dschu012** [comment]
Fix seems good enough to me.
