### ISSUE TITLE
reading and writing Plugy shared stash files

### ISSUE THREAD

**Issue by mgamperl** [dschu012/d2s#11]
Hi,

during using your api in a project of mine I though maybe I could contribute a feature to read and write Plugy shared stash files with your api.

I could create a pull request for that if you'd like to have this feature added. I have already developed it and my tests with a stash of 5000 items are fine but I would still need to create some testcases before I could finalize the pull request.

Just wanted to check if you are interested in that contribution.

Thanks!

**Comment by mgamperl** [comment]
created a pull request for that, see #15

**Comment by dschu012** [comment]
Thank. Merged.
