### ISSUE TITLE
[Bug] magical_name_ids are set to empty array before writing

### ISSUE THREAD

**Issue by mgamperl** [dschu012/d2s#18]
It seems that in `writeItem` the array containing the magical_name_ids is set to an empty array exactly before those ids should get written to file. This seems to be a bug as I can not find an explanation to why this should be correct. 

After fixing this, I can see that if the fixes from #17 and #16 are also merged the files written are nearly identical to the files read. I'm still investigation what are the remaining differences but I will open other bugs for that.

```typescript
 case Quality.Crafted:
              _writeBits(writer, _lookupRareId(item.rare_name, constants), start, offset, 8);
              offset += 8;
              _writeBits(writer, _lookupRareId(item.rare_name2, constants), start, offset, 8);
              offset += 8;
              item.magical_name_ids = []; //<<<--- this is problematic
              for (let i = 0; i < 6; i++) {
                  let magical_name_id = item.magical_name_ids[i];
                  if (magical_name_id) {
```
pull request will follow

**Comment by dschu012** [comment]
Not sure why I'd would've done that. Looks accidental to me.
