### ISSUE TITLE
[Proposal] Code Formatting Rules

### ISSUE THREAD

**Issue by mgamperl** [dschu012/d2s#22]
As I'm doing some pull requests and changes in that library, could we agree on what formating rules should be used?
Is there anything specific you have used in the past so that I can adjust my editor accordingly?

If you are using nothing specific I would suggest to use prettier as it is easy to use and provides sane defaults. 

Please let's discuss that  also ;)

**Comment by dschu012** [comment]
Nothing specifically I've used in the past (actually this was my first time using typescript), but feel free to add a linter as a dev dependency. I'm sure any rules would be better than nothing.
