### ISSUE TITLE
Opened D2R save files and saved as D2 didn't appears in D2 game.

### ISSUE THREAD

**Issue by UnclWish** [dschu012/d2s#32]
I tried to save D2R saves as D2 save. I thought that https://dschu012.github.io/d2s/
will convert D2R saves into usual D2 save.
Is it possible to implement?

**Comment by dschu012** [comment]
Can you share the save, I just tested it with one of mine successfully.

**Comment by UnclWish** [comment]
[D2Rsave.zip](https://github.com/dschu012/d2s/files/6473294/D2Rsave.zip)
Here is D2R save file. I just open Sets-I.d2s with https://dschu012.github.io/d2s/ pressing "browse" than press to "Save D2"
Looks like nothing changes. Even CRC32 of new file is the same...

**Comment by dschu012** [comment]
Ah, stupid mistake on my side. Fixed now. Just tested your save and it worked for me.

**Comment by UnclWish** [comment]
Thanks!
