### ISSUE TITLE
Undefined error in `char.header.right_swap_skill = constants.skills[reader.ReadUInt32()].s`

### ISSUE THREAD

**Issue by ktunkiewicz** [dschu012/d2s#40]
`default_header.js:26`
```
char.header.right_swap_skill = constants.skills[reader.ReadUInt32()].s; //0x0084
```

throws undefined because `reader.ReadUInt32()` returns `262198`.

Save file attached. [Bone.d2s.zip](https://github.com/dschu012/d2s/files/7963673/Bone.d2s.zip)

Fixed temporarily by adding a ternary operator that checks for undefined first, not sure if that's correct way of dealing with this but it seams to read all other stuff fine. I'm not even able to verify this because I don't have D2R, I'm writing a script for my friend.

**Comment by zeddicus-pl** [comment]
Ah, I'm sorry, that was for 2.0.4 and you made quite lot of changes recently, including using `?.s` in the above.

**Comment by ktunkiewicz** [comment]
Ah, I'm sorry, that was for 2.0.4 and you made quite lot of changes recently, including using ?.s in the above.
