### ISSUE TITLE
Cannot upload d2s file since 2.5 version

### ISSUE THREAD

**Issue by SPIRINE19** [dschu012/d2s#58]
Hello
First of all thank you very much for this page.
Since 2.5 I am unable to upload a d2s file to https://dschu012.github.io/d2s/ ?
Got OS in HC by a pindle minion because I was under amplify damage. 1005 hp gone like that !
So I wanted to use this functionality, but the file doesn't load anymore.

Could you please have a look in your script ? <3

**Comment by dtandersen** [comment]
https://news.blizzard.com/en-us/diablo2/23827590/diablo-ii-resurrected-patch-2-5-now-live

Save Data Changes
Some changes to save data have been made in "ItemStatCost.txt". If an existing single player mod has edited these values, then their mod's saves may become corrupted when migrating old saves to the new save version. It is recommended to create backups of existing saves before loading them.

"damageresist" and "magicresist"
Save Bits: 8 -> 9
Save Add: 0 -> 200
"fireresist", "lightresist", "coldresist", and "poisonresist"
Save Bits: 8 -> 9
Save Add: 50 -> 200

**Comment by dschu012** [comment]
this should hopefully be fixed now. I'll close this issue in a day or two if no further issues w/ it come up.

**Comment by SPIRINE19** [comment]
Good evening Daniel,
I confirm that the issue is fixed.
Thank you very much for your time on solving it.
Much appreciated. If you accept small donations, just pm me.

Take care.
