### ISSUE TITLE
2.5 Bugs, and 2.2.5 Grail bugs.

### ISSUE THREAD

**Issue by YuzuYellow** [dschu012/d2s#61]
So, with 2.5 + 2.2.4 the shared stash has bugged out, along with 3 of my characters

This now works, 

With 2.5 + 2.2.5 3 of my characters still cannot be read. This occured at the same time as the stash bug.

However, Shared stash is now working.

3 of my characters are not being loaded by the program. I've included all 3 character files to better aid you in identifying the issue

[3 Characters.zip](https://github.com/dschu012/d2s/files/9650602/3.Characters.zip)

**Comment by dtandersen** [comment]
Raised a new level 1 necro to 99 and I can't start a game w/ it.

**Comment by dtandersen** [comment]
I was able to do a barb on https://d2s.dschu012.dev/ but not https://dschu012.github.io/d2s/

**Comment by zeddicus-pl** [comment]
Watch this issue for updates: https://github.com/dschu012/d2s/issues/63
