### ISSUE TITLE
2.5 Sunder Charms load error

### ISSUE THREAD

**Issue by spg-stany** [dschu012/d2s#63]
Uncaught (in promise) Error: Save Bits is undefined for stat: 192:unused192 at position 7339
    at m (d2s.bundle.min.js:1:65618)
    at d2s.bundle.min.js:1:60289
    at d2s.bundle.min.js:1:53372

Save file
https://drive.google.com/file/d/10G3mWx6CJ2Sx3zGO7Gh_6rSX5YbC9RT7/view?usp=sharing

**Comment by dschu012** [comment]
ya... the txt files that are used right now for saves are from 1.13c. need to rewrite that code to read the jsons + txts.

**Comment by zeddicus-pl** [comment]
Hey @dschu012 i was just going to start digging into these new saves to figure out the new properties, but I guess I should wait for you and everything is in these new txt files right?
I only habe one concern - if you make a new "constants" source, because it is a parametr to most functions, the "automatic" recognition of the save version will not work properly, and my app really needs this. Would be great if you could do it in a way that constants source is selected based on the version of save, while it is being read.

**Comment by dschu012** [comment]
so my comment was more so mentioning what I think should happen. however I dont really have time to support this project now or in the near future, so it wasnt work I was planning on doing (I'll gladly merge PRs if someone wants to contribute). perhaps for your use case expose a method to get the version of the save in the header, and then the app consuming it can decide what constant source to pass in based on that (1.13c/2.4/2.5/etc..)?

**Comment by ktunkiewicz** [comment]
Sounds like a good idea @dschu012 .

I'm happy to provide PRs, I just don't know enough about the Diablo's TXT files. My plan to fixing this was basically to reverse engineer the magical properties of Sunder charms from the save files. I have no idea how to do it differently.

So, is this script creating the "constants" out of .txt files? https://github.com/dschu012/d2s/blob/master/src/data/parser.ts

Do I just run it on D2R files and that's it?

**Comment by dschu012** [comment]
https://github.com/dschu012/d2s/blob/master/tests/data/parser.spec.ts that unit test is what I would use with 1.13c to create that https://github.com/dschu012/d2s/blob/master/src/data/versions/96_constant_data.ts. I never ran it on D2R, but there were significant enough changes that that code probably doesnt work as is. But ya, basically you'd need to run that script (or something similar w/ changes) on D2R's files. I did do that myself the other day, but the resulting file was smaller than the 1.13c one, which didn't seem right.

**Comment by dschu012** [comment]
eh. I had some time to look at it quick this morning. I think the https://github.com/dschu012/d2s/blob/master/src/data/versions/96_constant_data.ts (or the js version https://github.com/dschu012/d2s/releases/download/v2.0.23/constants_99.bundle.min.js) should have everything right to work w/ the lib now.... I didn't really do a lot to verify that though.

**Comment by dschu012** [comment]
charstats.txt has a column `StrAllSkills` which points to the string the game uses for all skills for that class. For amazon the "key" for that string (used for localization) is `ModStr3a` in

1.13c
string.txt
```
ModStr3a	to Amazon Skill Levels
```

2.5
item-modifiers.json
```
  {
    "id": 3525,
    "Key": "ModStr3a",
    "enUS": "%+d to Amazon Skill Levels",
```

It's just how the string is in the files. Seems blizz changed it.

**Comment by zeddicus-pl** [comment]
that doesn't make sense because the 192 does exist... I'll check the code
![image](https://user-images.githubusercontent.com/79473394/194085619-a291cf32-7edf-4969-b7cc-e15bf3a0d750.png)

**Comment by zeddicus-pl** [comment]
@dschu012 it works!

The issue was that "cache" I made in my Patch 2.5 fix. I'll rework this thing to use 99 constants for 0x63 saves, and then that cache will not be needed.

![image](https://user-images.githubusercontent.com/79473394/194088369-8f0c3280-f44a-4560-8f6d-e72f9618a315.png)

![image](https://user-images.githubusercontent.com/79473394/194088413-7085d6e6-0a54-44bd-bc38-0149cafd35cb.png)

**Comment by dschu012** [comment]
Just pushed a test that looked to work for me

![image](https://user-images.githubusercontent.com/1458109/194088958-96f7b8cb-53e7-4e2f-8c21-70ad72285bf4.png)

**Comment by zeddicus-pl** [comment]
yeah @dschu012 , the issue is when you run entire `npm test` then it will error, because other saves are read, and the `_correctConstantsForVersion` cashes constants for `0x63`, so when all tests are run this save is being read with 96 constants *regardless* what constants you give in a parameter

**Comment by dschu012** [comment]
ya. I'm going to remove `_correctConstantsForVersion` I think...? should be unnecessary if you pass in the right constant?

**Comment by zeddicus-pl** [comment]
@dschu012 ah, I didn't read carefully - yes, you can remove that "fixing" function if you use correct constants.

What about making the constants optional? For my app that has to be detected automatically, so if that's a required parameter I will have to maintain my own fork and I'd love to avoid it... Reading version first, and the passing correct constants to the function means the files are read twice and for my app the efficiency of reading is very important too.

**Comment by dschu012** [comment]
If you can find a way to make the work cleanly w/o breaking the ability to pass in your own constants, feel free to make a PR. Reading the version of the save is only reading the first 8 bytes of the files so there isn't a whole lot of processing going on there.

**Comment by zeddicus-pl** [comment]
https://github.com/dschu012/d2s/pull/64
